ask_pupkin/urls.py
from django.conf.urls import patterns, include, url

from askapp.views import index, question, login, signup, profile, ask, like, best, tag
from askapp.forms import MyAuthenticationForm


urlpatterns = patterns('',
	url(r'^ask/$', ask), 
	url(r'^like/$', like),
	url(r'^best/$', best),
    url(r'^login/$', 'django.contrib.auth.views.login', {'authentication_form':MyAuthenticationForm}),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login'),
    url(r'^signup/$', signup),
    url(r'^settings/$', profile),
    url(r'^profile/$', profile),
    url(r'^question/(?P<qid>\d+)/$', question),
    url(r'^(?P<sort>\w+)/$', index),                
    url(r'/$', index),  
)

askapp/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    rating = models.IntegerField(default = 0)
    avatar = models.ImageField(upload_to = 'avatars/', null = True)
    def safe_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return '/noAvatar.jpeg'

class Tag(models.Model):
    tag = models.CharField(max_length = 33, unique = True)

class Question(models.Model):
    author = models.ForeignKey(Profile)
    title = models.CharField(max_length = 60)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)
    tags = models.ManyToManyField(Tag)
    best_answer = models.OneToOneField('Answer', null=True)
    votes = models.ManyToManyField(Profile, through='Vote', related_name='question_votes')
    rating = models.IntegerField(default = 0)
    def get_rating(self):
        likes = (Profile.objects.filter(vote__to_question=self, vote__is_like=True).count())
	dislikes = (Profile.objects.filter(vote__to_question=self, vote__is_like=False).count())
        return likes - dislikes

class Vote(models.Model):
    author = models.ForeignKey(Profile)
    to_question = models.ForeignKey(Question)
    is_like = models.BooleanField(default = False)
    class Meta:
        unique_together = ["author", "to_question"]

class Answer(models.Model):
    author = models.ForeignKey(Profile)
    to_question = models.ForeignKey(Question)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)
    #is_right = models.BooleanField(default = False)

askapp/forms.py
from django.forms import ModelForm, ModelChoiceField
from askapp.models import Question, Tag, Answer, Profile
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist 
from django.contrib.auth.models import check_password

class AnswerForm(ModelForm):	
	class Meta:
		model = Answer
		fields = ['text']
		widgets = {
            'text': forms.Textarea(attrs={'class': 'textarea width100', 'rows' : '3', 'placeholder':'Enter your answer here...'}),
        }	

class RegForm(forms.Form):
	username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Enter your username here...',
		'class' : 'input-xlarge'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password here...',
		'class' : 'input-xlarge'}))
	repeat_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Repeat password...',
		'class' : 'input-xlarge'}))
	email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter your e-mail here...',
		'class' : 'input-xlarge'}))
	avatar = forms.ImageField(required = False)
	
	
	def clean_repeat_password(self):
		if self.cleaned_data['password'] != self.cleaned_data['repeat_password'] :
			raise forms.ValidationError("The passwords you entered didn't match")
			
		return self.cleaned_data['repeat_password']	
	
	def clean_username(self):
		try:
			u = User.objects.get(username = self.cleaned_data['username'])		
			raise forms.ValidationError("This username is already taken")
		except ObjectDoesNotExist:
			return self.cleaned_data['username']
		
		
class SettingsForm(RegForm):
	user_id = 0
	def __init__(self, user_id, *args, **kwargs):
		super(SettingsForm, self).__init__(*args, **kwargs)		
		self.user_id = user_id
		
		self.fields['password'].required = False
		self.fields['repeat_password'].required = False
		self.fields['password'].widget.attrs['placeholder'] = 'Enter a new password here or leave empty'
		self.fields['password'].label = 'New password'
		

	current_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter your current password...',
		'class' : 'input-xlarge'}))
	avatar = forms.ImageField(required = False, widget=forms.FileInput)
	def clean_current_password(self):
		user = User.objects.get(pk = self.user_id)
		if not user.check_password(self.cleaned_data['current_password']):
			raise forms.ValidationError("Invalid password")			
		return self.cleaned_data['current_password']
		
	def clean_username(self):
		try:
			u = User.objects.get(username = self.cleaned_data['username'])	
			if u.pk != self.user_id:
				raise forms.ValidationError("This username is already taken")
		except ObjectDoesNotExist:
			pass
		return self.cleaned_data['username']
		

class MyAuthenticationForm(AuthenticationForm):    
	def __init__(self, *args, **kwargs):
		super(MyAuthenticationForm, self).__init__(*args, **kwargs)
		self.fields['password'].widget.attrs['placeholder'] = 'Enter your password here...'
		self.fields['username'].widget.attrs['placeholder'] = 'Enter your username here...'
    #username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Enter your username here...'}))
    #password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password here...'}))
    
class QuestionForm(ModelForm):
	tags = forms.CharField(required=False, 
		widget=forms.TextInput(attrs={'class': 'ask_tags span9', 'placeholder':'Example: tag1 tag2 tag3'}))
	class Meta:
		model = Question
		fields = ['title', 'text']
		widgets = {
            'text': forms.Textarea(attrs={'class': 'ask_text span9', 'rows' : '6', 'placeholder':'Enter your question here...'}),
            'title': forms.TextInput(attrs={'class': 'ask_title span9', 'placeholder':'Enter title here...'}),
        }
	def clean_tags(self):
		error_messages = []
		
		cleaned_tags = self.cleaned_data['tags'].split()
		
		if len(cleaned_tags) > 3:
			error_messages.append("you cannot add more than 3 tags")
		tag_len_err = False
		for i in range(0, len(cleaned_tags)):
			if len(cleaned_tags[i])>33:
				tag_len_err = True
		if tag_len_err:
			error_messages.append("tags must be less than 34 characters long")
		if len(error_messages):
			raise forms.ValidationError(error_messages)
		else:
			return cleaned_tags

    	
				
	
	

templates/answer_box.html
<div class="question_box row">    
    
    <div class="span8">  
		
		{% if q.best_answer_id = a.id %}
	       <div class="alert alert-success"> Best answer</div>
       {% endif %}
        <div class="answer">    
			{{a.text}}
        </div>
        <div class="answer_bottom_box">
		{% ifequal q.author_id user.profile.id %}
		
 		{% if not best_exists %}
			<button class="btn best_btn" data-ans="{{a.id}}" data-quest="{{q.id}}">This is the best answer</button>
        {% endif %}
        {% endifequal %}
        <a href="/user/{{q.author.user.username}}"><img class="answer_avatar" src="{{a.author.safe_avatar}}" /></a>
        <div class="answer_date">{{a.date_added}}</div>
        <div class="answer_username">{{a.author.user.username}}</div>
        </div>
    </div>
    
</div>

{% if q.best_answer_id = a.id %}
<br/>
{% endif %}

templates/ask.html
{% extends "base.html" %}

{% block content %}


<form class="form-horizontal" method="post" action="{% url 'askapp.views.ask' %}">
{% csrf_token %}
<fieldset>
        <legend class="margin0">
            <h2>Ask a question</h2>
        </legend>
        
        <br>
        <div class="control-group">
            <label  for="id_title">{{ form.title.label_tag }}</label>  
                {{ form.title }}
        </div>
        <div class="control-group">
            <label for="id_text">{{ form.text.label_tag }}</label>            
                {{ form.text }}            
        </div>   
        
        <div class="control-group">
            <label  for="id_tags">Tags (max 3):</label>            		
            <div class="red">{{ form.tags.errors }}</div>
                {{ form.tags }}
        </div>
       
            <button type="submit" class = "btn btn-primary ask_button" value="submit">Ask</button>
       
		
    </fieldset>
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    
    <link rel="stylesheet" type="text/css" href="http://localhost/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="http://localhost/style.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
           
</head>
<body>

<div class="navbar">
<div class="navbar-inner">
    <div class="container">
        <!--div class="row"-->
            <div class="span11 {% if user.is_authenticated %}line50{% endif %}">
                <a class="brand" {% if user.is_authenticated %}id="nav_brand50"{% endif %} href="/">Ask Pupkin</a>
                <form class="navbar-search">
                    <input type="text" class="search-query" placeholder="Search">
                </form>
                
                <div class="nav-collapse line50" >
				<ul class="nav">
					<li class="divider-vertical  {% if user.is_authenticated %}navbar_div50{% endif %}"></li>
					<li><a href="/hot/" {% if user.is_authenticated %}class="navbar_li50"{% endif %}>Hot questions</a></li>
					<li class="divider-vertical  {% if user.is_authenticated %}navbar_div50{% endif %}"></li>
					<li><a href="/recent/" {% if user.is_authenticated %}class="navbar_li50"{% endif %}>Recent questions</a></li>
				</ul></div>
                <div class="pull-right" >
                <a href="/ask/" class="btn btn-success">
                    Ask!
                </a>
                </div>
            </div>

            {% include "user.html" %} 
            
        <!--/div-->
    </div>
</div>
</div>
<!-- navbar end -->

    <div class="container">

        <div class="row">
            <div class="span9">
                {% block content %} 
				<p>main</p>
                {% endblock %}                       
            </div>
            <div class="span3">
                {% include "sidebar.html" %}
            </div>
        </div>
    </div>
</body>
</html>

templates/like_script.html
<script type="text/javascript">
		function getCookie(name) {
			var cookieValue = null;
			if (document.cookie && document.cookie != '') {
				var cookies = document.cookie.split(';');
				for (var i = 0; i < cookies.length; i++) {
					var cookie = jQuery.trim(cookies[i]);
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) == (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');
		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		$.ajaxSetup({
			beforeSend: function(xhr, settings) {
				if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});
		$(function(){
			$('.js-like').click(function(){
                    var $btn = $(this);
                    $.ajax({type : 'POST',
						url : '/like/',
						data : {'q_id' : $btn.data("q_id"), 'auth_id' : $btn.data("auth_id"), 'like' : $btn.data("like")},
						success : function(resp) {
							if(resp.status == 'ok'){								
								if(resp.new_rating < 0) {
									$btn.parent().find('.js-cnt').addClass('badge-error').removeClass('badge-success');
								} else {
									$btn.parent().find('.js-cnt').addClass('badge-success').removeClass('badge-error'); 
								}
								$btn.parent().find('.js-cnt').text(resp.new_rating);
							 } else {
								 alert(resp.error);
							 }
					     },
						
						dataType : 'json'}
                    )
                });
		});
		

         </script> 

templates/login.html
{% extends "base.html" %}
<link rel="stylesheet" type="text/css" href="style.css">
{% block content %}


<form class="form-horizontal" method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
    <fieldset>
        <legend>
            <h2>Log In</h2>
        </legend>
        {% if form.errors %}
        <div class="red">
			<!--{% for field, errors in form.errors.items %}
				{% for error in errors %}-->
		{{ form.errors }}
		</div>
		{% endif %}		
        
        <br>
        <div class="control-group">
            <label class="control-label" for="input_login">{{ form.username.label_tag }}</label>
            <div class="controls">
				{{ form.username }}
				<!--id-->
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="input_password">{{ form.password.label_tag }}</label>
            <div class="controls">
				{{ form.password }}
                <!--input type="password" class="input-xlarge" id="input_password" placeholder="Enter your password here..."-->
            </div>
        </div>
        <div class="form-actions transparent">
            <button type="submit" class="btn btn-primary">Log In</button>
            <a href="/signup/">Create new account</a>
        </div>

    </fieldset>
</form>


{% endblock content %}

templates/main.html
{% extends "base.html" %}

{% block content %}
<h2 class="title">{{header}}</h2>
<!--a href="/hot"">Show top questions instead...</a-->

{% include "like_script.html" %}

{% for q in questions %}

{% include "question_box.html" %}

{% endfor %}


{% with questions as items %}
{% include "pagination.html" %}
{% endwith %}



{% endblock content %}

templates/pagination.html
{% if items.has_previous or items.has_next %}
<div class="pagination">
    <ul>
		{% if items.has_previous %}
			<li><a href="?page={{items.previous_page_number}}">Prev</a></li>
        {% endif %}
        {% for pr in prev %}
        <li><a href="?page={{pr}}">{{pr}}</a></li>        
        {% endfor %}
        <li class="active">
            <a href="?page={{ items.number }}">{{ items.number }}</a>
        </li>
        {% if items.has_next %}			
			<li><a href="?page={{ items.next_page_number }}">{{ items.next_page_number }}</a></li>
        {% endif %}
        {% if dotdotdot %}
				<li><a href="?page={{ items.next_page_number }}">...</a></li>
		{% endif %}
		
		{% if answers.has_next %}
        {% ifnotequal items.next_page_number items.paginator.num_pages %}			
			<li><a href="?page={{ answers.paginator.num_pages }}">{{ items.paginator.num_pages }}</a></li>			
        {% endifnotequal %}
        {% endif %}
        
        {% if items.has_next %}	
			<li><a href="?page={{ answers.next_page_number }}">Next</a></li>
		{% endif %}
    </ul>
</div>
{% endif %}

templates/question.html
{% extends "base.html" %}

{% block content %}

{% include "like_script.html" %}

<script>
$(function(){
			$('.best_btn').click(function(){
				alert ('pumba');
				var $btn = $(this);
				$.ajax({type : 'POST',
					url : '/best/',
					data : {'a_id' : $btn.data("ans"), 'q_id' : $btn.data("quest")},
					success : function(resp) {
						if(resp.status == 'ok'){			
							$btn.parent().parent().prepend('<div class="alert alert-success"> Best answer</div>');
							$('.js-answers').prepend('<br/>');
							$btn.parent().parent().parent().prependTo('.js-answers');
							$('.js-answers').find('.best_btn').remove();	
						 } else {
							 alert(resp.error);
						 }
					 },
					
					dataType : 'json'});
			});
		});
</script>

<h2 class="title">Question:</h2>


{% include "question_box.html" %}
<h2 class="title">
{% ifnotequal answers.paginator.count 0 %}

		{{answers.paginator.count}} 
	answers:
{% else %}		
 No answers.
{% endifnotequal %}	

</h2>
<div class="js-answers">
{% for a in answers %}
      {% include "answer_box.html" %}
{% endfor %}
</div>
{% with answers as items %}
{% include "pagination.html" %}
{% endwith %}

{% if user.is_authenticated %}
<form class="row form-horizontal" method="post" action="{{request.path}}">
{% csrf_token %}        
          <legend>Your answer:</legend>
          
          <div class="control-group">          
              {{form.text}}         
          </div>   
          <button type="submit" class="btn btn-primary">Answer</button>        
</form>
{% endif %}
{% endblock content %}

templates/question_box.html
<div class="question_box row">
    <div class="span1 question_rating_box">       
		
        <i class="js-like icon-chevron-up" data-q_id="{{q.id}}" data-auth_id="{{q.author_id}}" data-like="1"></i><br/>
        {% if q.rating >= 0 %}
			<span class="badge badge-success question_rating js-cnt">
		{% else %}
			<span class="badge badge-error question_rating js-cnt">
		{% endif %}
			{{q.rating}}
			</span><br/>
        <i class="icon-chevron-down js-like" data-q_id="{{q.id}}" data-auth_id="{{q.author_id}}" data-like="0"></i>
    </div>
    
    <div class="span7 left10">
        <a href="/question/{{q.id}}/">
			{% if question_brief %}
            <h3>{{q.title|truncatechars:60}}</h3>
            {% else %}	
            <h3>{{q.title}}</h3>
            {% endif %}
        </a>
        {% if question_brief %}
        <div class="question_brief">		
            {{q.text|truncatechars:222}}
        {% else %}	
        <div class="question">    
			{{q.text}}
		{% endif %}	
        </div>
        <div class="question_bottom_box">
        <div class="question_bottom">
            <a href="/question/{{q.id}}/"><i class="icon-comment"></i> answer({{q.answer_set.count}})</a>
           
           {% ifnotequal q.tags.count 0 %}
            Tags:
            {% for tg in q.tags.all %}            
				<a href="/?tag={{tg.tag}}">{{tg.tag}}</a>
			{% endfor %}
           {% endifnotequal %}
            
            
        </div>
        
        <a href="/user/{{q.author.user.username}}"><img class="question_avatar" src="{{q.author.safe_avatar}}" /></a>
        <div class="question_date" >{{q.date_added}}</div>
        <div class="question_username">{{q.author.user.username}}</div>
        </div>
    </div>
    
</div>

templates/settings.html
{% extends "base.html" %}
{% block content %}

<form class="form-horizontal" method="post" action="{% url 'askapp.views.profile' %}"  enctype="multipart/form-data">
	{% csrf_token %}
    <fieldset>
        <legend>
            <h2>Settings: {{user.username}}</h2>
        </legend>
		{{ form.non_field_errors }}
        <div class="control-group">
            <label class="control-label" for="input_login">Username</label>
            <div class="controls">
                {{form.username}}
				<div class="red">{{ form.username.errors }}</div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="input_email">E-mail</label>
            <div class="controls">
                {{form.email}}  
				<div class="red">{{ form.email.errors }}</div>
            </div>
        </div>    
        <div class="control-group">
            <label class="control-label" for="id_password">{{form.current_password.label_tag}}</label>
            <div class="controls">
				{{form.current_password}}
				<div class="red">	{{ form.current_password.errors }}</div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_password">{{form.password.label_tag}}</label>
            <div class="controls">
				{{form.password}}
				<div class="red">	{{ form.password.errors }}</div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_repeat_password">{{form.repeat_password.label_tag}}</label>
            <div class="controls">
				{{form.repeat_password}}
				<div class="red">	{{ form.repeat_password.errors }}</div>
            </div>
        </div>    
        <div class="control-group">
            <label class="control-label" for="input_avatar">Upload avatar</label>
            <div class="controls">
				{% if user.profile.avatar %}       	 
					<a class="thumbnail inline">					
						<img src="{{ user.profile.avatar.url }}"/>  
					</a> 
					<br/>
                {% endif %}                
                {{form.avatar}}  
				<div class="red">	{{ form.avatar.errors }}</div>
				<br/>
				{% if user.profile.avatar %}   
					<label class="checkbox">
					<input type="checkbox" name="remove"/>
					Remove avatar
					</label>
                {% endif %}
            </div>
            
				
        </div>

        <div class="form-actions transparent">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>

    </fieldset>
</form>


{% endblock content %}

templates/sidebar.html
{% load inclusion %}
<!--h2 class="title">Popular tags</h2>
<a class="popular_tag" href="tag1">popular tag1</a>
<a class="popular_tag red" href="tag2">popular tag2</a>
<a class="popular_tag large" href="tag3">tag3</a>
<a class="popular_tag" href="tag4">tag4</a>
<a class="popular_tag large" href="tag1">popular tag1</a>
<a class="popular_tag large" href="tag2">tag2</a>
<a class="popular_tag red larger" href="tag3">tag3</a>
<a class="popular_tag green larger" href="tag4">tag4</a>
<a class="popular_tag" href="tag1">tag1</a>
<a class="popular_tag larger" href="tag2">tag2</a>
<a class="popular_tag orange" href="tag3">tag3</a>
<a class="popular_tag" href="tag4">tag4</a-->

{% best_tags %}
{% best_users %}

templates/signup.html
{% extends "base.html" %}
{% block content %}

<form class="form-horizontal" method="post" action="{% url 'askapp.views.signup' %}"  enctype="multipart/form-data">
{% csrf_token %}
    <fieldset>
        <legend>
            <h2>Registration</h2>
        </legend>
		{{ form.non_field_errors }}
        <div class="control-group">
            <label class="control-label" for="id_login">{{form.username.label_tag}}</label>            
            <div class="controls">
				{{form.username}}  
				<div class="red">{{ form.username.errors }}</div>           
            </div>            
        </div>
        <div class="control-group">
            <label class="control-label" for="id_email">{{form.email.label_tag}}</label>
            <div class="controls">
				{{form.email}}
				<div class="red">	{{ form.email.errors }}</div>				
            </div>
        </div>        
        <div class="control-group">
            <label class="control-label" for="id_password">{{form.password.label_tag}}</label>
            <div class="controls">
				{{form.password}}				
				<div class="red">{{ form.password.errors }}</div>				
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_repeat_password">{{form.repeat_password.label_tag}}</label>
            <div class="controls">
				{{form.repeat_password}}				
				<div class="red">	{{ form.repeat_password.errors }}</div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="input_avatar">Upload avatar</label>
            <div class="controls">                 
                {{ form.avatar }}
                <div class="red">{{ form.avatar.errors }}</div>
            </div>
        </div>

        <div class="form-actions transparent">
            <button type="submit" class="btn btn-primary">Sign up</button>            
        </div>

    </fieldset>
    <input type="hidden" name="next" value="{{ next }}" />
</form>


{% endblock content %}

templates/signup2.html
{% extends "base.html" %}
{% block content %}


<form class="form-horizontal" method="post" action="{% url 'askapp.views.signup2' %}">
{% csrf_token %}

    {{form}}
    <button type="submit" class="btn btn-primary">Sign Up</button>
</form>


{% endblock content %}

templates/user.html
{% if user.is_authenticated %}
            <div class="span3 pull-right">
                <div class="row">
                    <div class="span1">

                        <img id="top_right_avatar" src="{{ user.profile.safe_avatar }}" />
                    </div>
                    <div class="span2" id="user_buttons">
                        
                            <div id="top_right_username">
                                <a href="/profile/" class="white">{{user.username}}</a>
                            </div>
                        
							<div id="top_right_settings_row">

								<a href="/profile/" class="white">settings</a>

								<a href="/logout/" class="white" id="top_right_logout">log out</a>

							</div>
						
                    </div>
                </div>
            </div>
{% else %}
<div class="span2 pull-right"id="user_buttons_not_logged" >
<div id="top_right_settings_row" >

        <a href="/login/?next={{request.path}}" class="white">log in</a>

		<a href="/signup/?next={{request.path}}" class="white" id="top_right_logout">sign up</a> 
</div>
</div>
{% endif %}            